config/routes.rb
Yeshi::Application.routes.draw do
  use_doorkeeper

  constraints subdomain: ENV['SUBDOMAIN'] do
    resources :nodes do
      resources :topics, only: [:new, :create]
    end
    resources :sections
    resources :topics do
      resources :replies
    end
    resources :articles, only: [:index, :show] do
      get '/tags/:tag', to: 'articles#tag', as: :tag, on: :collection
      get '/tags', to: 'articles#tags', as: :tags, on: :collection
      resources :comments, only: [:index,:create]
    end
    get '/categories/:category', to: 'commodities#category', as: :category
    get '/categories', to: 'commodities#categories', as: :categories
    resources :posts, only: [:index, :show] do
      get :ajax, on: :collection
      resources :comments, only: [:index,:create]
    end
    resources :comments, only: [:index, :show, :create]
    resources :notifications ,except: [:edit,:update,:new,:create] do
      get :read,on: :collection
      #member do 
      #post :accept
      #post :deny
      #end
    end

    resources :chat_messages, only: [:new, :create]
    resources :got_chat_messages, only: [:index, :show, :destroy]
    resources :traders, only: [:index, :show, :create] do
      get :contact, to: 'traders#contact', on: :member
      resources :locations, only: [:index]
      resources :commodities, only: [:index]
      resources :groups, only: [:index]
    end
    resources :groups, only: [:index, :show] do
      resources :commodities, only: [:index]
      resources :comments, only: [:index,:create]
    end

    resources :locations, only: [:index]
    resources :commodities, only: [:index, :show] do
      resources :comments, only: [:index,:create]
    end
    authenticated :user do
      root :to => 'home#index'
    end
    root :to => "home#index"
    get '/contact', :to => "home#contact", as: :system_contact
    get '/download', :to => "home#download", as: :download
  end

  constraints subdomain: ENV['USER_SUBDOMAIN'] do
    devise_for :users, controllers: {
      omniauth_callbacks: :authentications,
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    }
    scope module: 'user' do
      root to: 'home#index', as: :user_home
      #get 'authentications', to: 'home#authentications', as: :user_authentications
      resources :posts do
        get :ajax, on: :collection
      end
      resources :authentications
      resources :chat_messages, only: [:new, :create], as: :user_chat_messages
      resources :got_chat_messages, only: [:index, :show, :destroy], as: :user_got_chat_messages
      resources :commodities, only: [:index, :show] do
        resources :chat_messages, only: [:new, :create]
      end

      resources :comments, only: [:index, :destroy]
      resources :mp_users

    end
  end

  constraints subdomain: ENV['TRADER_SUBDOMAIN'] do
    #devise_for :users
    scope module: 'trader' do
      resources :contacts, except: [:show]
      resources :traders, only: [:index, :create, :update]
      resources :locations, except: [:edit, :update]
      resources :groups do
        resources :commodities
        get :bulk_add, on: :member
        put :bulk_add_commodities, on: :member
      end
      resources :pictures
      resources :bills, except: [:new, :show] do
        get :dashboard, on: :collection
      end
      resources :commodities, except: [:new] do
        resources :bills, only: [:index, :new]
      end
      root :to => 'home#index', as: :trader_home
      get '/dashboard' => 'bills#dashboard'
    end
  end

  constraints subdomain: ENV['ADMIN_SUBDOMAIN'] do
    scope module: 'admin' do
      resources :articles do
        post :publish, on: :member
      end
      resources :apks do
        get :updated_version, on: :member
      end
      resources :users
      resources :ads
      resources :comments
    end
  end

  constraints subdomain: ENV['API_SUBDOMAIN'] do
    scope module: 'api' do
      namespace :v1 do
        # another api routes
        get '/me' => "credentials#me"
        get '/dashboard' => "credentials#dashboard"
        post '/reg' => "registrations#create"
        #post '/test' => "registrations#test"
        resources :got_chat_messages, only: [:index, :show, :destroy]
        resources :chat_messages, only: [:create]
        resources :locations, only: [:index, :create, :destroy]
        resources :business_hours, only: [:index, :create, :update, :destroy]
        resources :groups, only: [:index, :create, :update, :destroy, :show] do
          resources :commodities, only: [:index, :create]
          put :bulk_add_commodities, on: :member
        end

        resources :commodities, only: [:index, :create, :update, :destroy, :show] do
          resources :bills
        end
        resources :bills, only: :index do
          get :dashboard, on: :collection
        end
        #resources :notifications ,except: [:edit,:update,:new,:create] do
          #get :read,on: :collection
          #get :status,on: :collection
          #member do 
            #post :accept
            #post :deny
          #end
        #end
      end
    end
  end

  constraints subdomain: ENV['MP_SUBDOMAIN'] do
    scope module: 'mp' do
      root to: 'home#index', as: :mp, via: [:get]
      post '/' => "home#create"
    end
  end

end

app/models/node.rb
class Node
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::BaseModel
  field :name, type: String
  field :summary, type: String
  field :sort, type: Integer, default: 0

  has_many :topics
  belongs_to :section

  index :section_id => 1

  validates_presence_of :name, :summary, :section
  validates_uniqueness_of :name

  has_and_belongs_to_many :followers, :class_name => 'User', :inverse_of => :following_nodes

  #scope :hots, desc(:topics_count)
  scope :sorted, desc(:sort)
end

app/controllers/nodes_controller.rb
class NodesController < InheritedResources::Base
  before_filter :authenticate_admin!, except: [:show]
  add_crumb(I18n.t("controller.sections")) { |instance| instance.send :sections_path }

  def show
    show! do
      add_crumb(@node.name, node_path(@node))
      @topics = @node.topics.last_actived.fields_for_list.page(params[:page])
    end
  end

  protected
  def collection
    @nodes ||= end_of_association_chain.sort
  end
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/nodes/_form.html.erb
<%= simple_form_for(@node) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :section, collection: Section.all, include_blank: false %>
    <%= f.input :sort %>
    <%= f.input :name %>
    <%= f.input :summary, as: :kindeditor, owner_id: current_user._id, allowFileManager: false, link: false, input_html: {simple_mode: true} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/nodes/_header.html.erb
<div class="node-topics-header">
  <div class="col-md-6 col-lg-6">
    <strong>标题</strong>
  </div>
  <div class="col-md-2 col-lg-2">
    <strong>作者</strong>
  </div>
  <div class="col-md-2 col-lg-2">
    <strong>回复/查看</strong>
  </div>
  <div class="col-md-2 col-lg-2">
    <strong>最后发表</strong>
  </div>
  <div class="clearfix"></div>
</div>

app/views/nodes/_new_and_page.html.erb
<div class="node-new-and-page">
  <% if params[:node] %>
    <div class="pull-left mtb20 pl">
      <%= button_to '发贴', new_node_topic_path(params[:node]), method: :get, class: 'btn btn-primary' %>
    </div>
  <% end %>
  <% if params[:pages] %>
    <div class="pull-right">
      <%= paginate params[:pages] %>
    </div>
  <% end -%>
  <div class="clearfix"></div>
</div>

app/views/nodes/edit.html.erb
<h1>Editing node</h1>

<%= render 'form' %>

<%= link_to 'Show', @node %> |
<%= link_to 'Back', nodes_path %>

app/views/nodes/index.html.erb
<%= link_to "新建", new_node_path, class: 'btn btn-primary' %>
<% @nodes.group_by(&:section).each do |section,nodes| %>
  <div class="">
    <h3><%= section.name %></h3>
    <% nodes.each do |node| %>
      <div class="">
        <%= link_to node.name, node %>,
        <%= link_to '修改', edit_node_path(node) %>
        <%= link_to '删除', node, method: :delete, data: { confirm: '确定？' } %>

      </div>
    <% end -%>

  </div>
<% end -%>

<%= link_to "新建", new_node_path, class: 'btn btn-primary' %>

app/views/nodes/new.html.erb
<h1>New node</h1>

<%= render 'form' %>

<%= link_to 'Back', nodes_path %>

app/views/nodes/show.html.erb
<div class="panel panel-default"id="node_<%= @node.id %>">
  <div class="panel-heading">
    <h1 class="panel-title topic-title">
      <%= title @node.name %>
    </h1>
    <div class="meta">
      <%= @node.summary.html_safe %>
    </div>
  </div>
  <div class="panel-body p0 topics">
    <% if @topics.any? %>
      <%= render @topics %>
    <% else %>
      <p> 暂无帖子，还不赶快抢沙发？ </p>
    <% end %>
  </div>
  <div class="panel-footer">
    <%= render "nodes/new_and_page", params: {pages: @topics, node: @node} %>
  </div>
</div>