config/routes.rb
Yeshi::Application.routes.draw do
  use_doorkeeper

  constraints subdomain: ENV['SUBDOMAIN'] do
    resources :nodes do
      resources :topics, only: [:new, :create]
    end
    resources :sections
    resources :topics do
      resources :replies
    end
    resources :articles, only: [:index, :show] do
      get '/tags/:tag', to: 'articles#tag', as: :tag, on: :collection
      get '/tags', to: 'articles#tags', as: :tags, on: :collection
      resources :comments, only: [:index,:create]
    end
    get '/categories/:category', to: 'commodities#category', as: :category
    get '/categories', to: 'commodities#categories', as: :categories
    resources :posts, only: [:index, :show] do
      get :ajax, on: :collection
      resources :comments, only: [:index,:create]
    end
    resources :comments, only: [:index, :show, :create]
    resources :notifications ,except: [:edit,:update,:new,:create] do
      get :read,on: :collection
      #member do 
      #post :accept
      #post :deny
      #end
    end

    resources :chat_messages, only: [:new, :create]
    resources :got_chat_messages, only: [:index, :show, :destroy]
    resources :traders, only: [:index, :show, :create] do
      get :contact, to: 'traders#contact', on: :member
      resources :locations, only: [:index]
      resources :commodities, only: [:index]
      resources :groups, only: [:index]
    end
    resources :groups, only: [:index, :show] do
      resources :commodities, only: [:index]
      resources :comments, only: [:index,:create]
    end

    resources :locations, only: [:index]
    resources :commodities, only: [:index, :show] do
      resources :comments, only: [:index,:create]
    end
    authenticated :user do
      root :to => 'home#index'
    end
    root :to => "home#index"
    get '/contact', :to => "home#contact", as: :system_contact
    get '/download', :to => "home#download", as: :download
  end

  constraints subdomain: ENV['USER_SUBDOMAIN'] do
    devise_for :users, controllers: {
      omniauth_callbacks: :authentications,
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    }
    scope module: 'user' do
      root to: 'home#index', as: :user_home
      #get 'authentications', to: 'home#authentications', as: :user_authentications
      resources :posts do
        get :ajax, on: :collection
      end
      resources :authentications
      resources :chat_messages, only: [:new, :create], as: :user_chat_messages
      resources :got_chat_messages, only: [:index, :show, :destroy], as: :user_got_chat_messages
      resources :commodities, only: [:index, :show] do
        resources :chat_messages, only: [:new, :create]
      end

      resources :comments, only: [:index, :destroy]
      resources :mp_users

    end
  end

  constraints subdomain: ENV['TRADER_SUBDOMAIN'] do
    #devise_for :users
    scope module: 'trader' do
      resources :contacts, except: [:show]
      resources :traders, only: [:index, :create, :update]
      resources :locations, except: [:edit, :update]
      resources :groups do
        resources :commodities
        get :bulk_add, on: :member
        put :bulk_add_commodities, on: :member
      end
      resources :pictures
      resources :bills, except: [:new, :show] do
        get :dashboard, on: :collection
      end
      resources :commodities, except: [:new] do
        resources :bills, only: [:index, :new]
      end
      root :to => 'home#index', as: :trader_home
      get '/dashboard' => 'bills#dashboard'
    end
  end

  constraints subdomain: ENV['ADMIN_SUBDOMAIN'] do
    scope module: 'admin' do
      resources :articles do
        post :publish, on: :member
      end
      resources :apks do
        get :updated_version, on: :member
      end
      resources :users
      resources :ads
      resources :comments
    end
  end

  constraints subdomain: ENV['API_SUBDOMAIN'] do
    scope module: 'api' do
      namespace :v1 do
        # another api routes
        get '/me' => "credentials#me"
        get '/dashboard' => "credentials#dashboard"
        post '/reg' => "registrations#create"
        #post '/test' => "registrations#test"
        resources :got_chat_messages, only: [:index, :show, :destroy]
        resources :chat_messages, only: [:create]
        resources :locations, only: [:index, :create, :destroy]
        resources :business_hours, only: [:index, :create, :update, :destroy]
        resources :groups, only: [:index, :create, :update, :destroy, :show] do
          resources :commodities, only: [:index, :create]
          put :bulk_add_commodities, on: :member
        end

        resources :commodities, only: [:index, :create, :update, :destroy, :show] do
          resources :bills
        end
        resources :bills, only: :index do
          get :dashboard, on: :collection
        end
        #resources :notifications ,except: [:edit,:update,:new,:create] do
          #get :read,on: :collection
          #get :status,on: :collection
          #member do 
            #post :accept
            #post :deny
          #end
        #end
      end
    end
  end

  constraints subdomain: ENV['MP_SUBDOMAIN'] do
    scope module: 'mp' do
      root to: 'home#index', as: :mp, via: [:get]
      post '/' => "home#create"
    end
  end

end

app/models/topic.rb
# coding: utf-8
require "auto-space"
class Topic
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::BaseModel
  #include Mongoid::MarkdownBody
  #include Mongoid::CounterCache
  #include Mongoid::MagicCounterCache
  field :title, type: String
  field :body, type: String
  #field :body_html
  field :replied_at, type: DateTime
  field :excellent, type: Boolean, default: false
  field :last_active_mark, type: Integer

  # 回复过的人的 ids 列表
  field :follower_ids, :type => Array, :default => []
  field :visits, :type => Integer, default: 0
  field :last_reply_user_name, type: String

  belongs_to :user, :inverse_of => :topics, counter_cache: true
  #counter_cache :name => :user, :inverse_of => :topics
  belongs_to :node, counter_cache: true
  #counter_cache :name => :node, :inverse_of => :topics
  #counter_cache :user
  #counter_cache :node
  belongs_to :last_reply_user, :class_name => 'User'
  belongs_to :last_reply, :class_name => 'Reply'
  has_many :replies, :dependent => :destroy

  validates_presence_of :user_id, :title, :body, :node_id

  index :node_id => 1
  index :user_id => 1
  index :last_active_mark => -1
  #index :likes_count => 1
  #index :suggested_at => 1
  index :excellent => -1

  #counter :hits, :default => 0

  delegate :login, :to => :user, :prefix => true, :allow_nil => true
  delegate :body, :to => :last_reply, :prefix => true, :allow_nil => true

  # scopes
  scope :last_actived, desc(:last_active_mark)
  # 推荐的话题
  #scope :suggest, -> { where(:suggested_at.ne => nil).desc(:suggested_at) }
  scope :fields_for_list, -> { without(:body)}#,:body_html) }
  #scope :high_likes, -> { desc(:likes_count, :_id) }
  scope :high_replies, -> { desc(:replies_count, :_id) }
  scope :no_reply, -> { where(:replies_count => 0) }
  #scope :popular, -> { where(:likes_count.gt => 5) }
  scope :without_node_ids, Proc.new { |ids| where(:node_id.nin => ids) }
  scope :excellent, -> { where(:excellent.gte => 1) }

  before_save :auto_space_with_title
  def auto_space_with_title
    self.title.auto_space!
  end

  before_create :init_last_active_mark_on_create
  def init_last_active_mark_on_create
    self.last_active_mark = Time.now.to_i
  end

  def push_follower(uid)
    return false if uid == self.user_id
    return false if self.follower_ids.include?(uid)
    self.push(follower_ids: uid)
  end

  def pull_follower(uid)
    return false if uid == self.user_id
    self.pull(follower_ids: uid)
  end

  def update_last_reply(reply)
    # replied_at 用于最新回复的排序，如果贴着创建时间在一个月以前，就不再往前面顶了
    self.last_active_mark = Time.now.to_i if self.created_at > 1.month.ago
    self.replied_at = Time.now
    self.last_reply = reply 
    self.last_reply_user = reply.user
    self.last_reply_user_name = reply.user.try(:name) || nil
    self.save
  end

  def excellent?
    !!self.excellent
  end
end

app/controllers/topics_controller.rb
class TopicsController < InheritedResources::Base
  before_filter :authenticate_user!, only: [:new, :create]
  before_filter :authenticate_admin!, only: [:edit, :update, :destroy]
  belongs_to :node, optional: true
  add_crumb(I18n.t("controller.sections")) { |instance| instance.send :sections_path }

  def create
    @topic = current_user.topics.new(params[:topic])
    create!
  end

  def show
    show! do
      add_crumb(@topic.node.name, node_path(@topic.node)) if @topic.node
      add_crumb(@topic.title, topic_path(@topic))
      Topic.update_counters @topic.id, visits: 1
      @replies = @topic.replies
    end
  end

  protected
  def collection
    @topics ||= end_of_association_chain.last_actived.fields_for_list.page params[:page]
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= simple_form_for(@topic) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :node, collection: Section.all, as: :grouped_select, group_method: :nodes, include_blank: false, selected: @node.try(:id)  %>
    <%= f.input :title %>
    <%= f.input :body, as: :kindeditor, owner_id: current_user._id, allowFileManager: false, link: false, input_html: {simple_mode: true} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<div class="topic">
  <div class="col-md-11 col-lg-11 oh">
    <h4>
      <%= link_to topic.title.block(50), topic %>
    </h4>
    <div class="meta">
      <%= topic.user %>
      •
      最后由<%= topic.last_reply_user_name %>回复
      •
      <%= topic.visits %>次阅读
    </div>
  </div>
  <div class="col-md-1 col-lg-1">
    <div class="replies">
      <%= link_to topic.replies.count, topic_path(topic) + "#reply_#{topic.replies.count}", class:"count" %>
    </div>
  </div>
  <div class="clearfix"></div>
</div>

app/views/topics/_topic_show.html.erb
<div class="panel panel-default" id="<%= @topic.id %>">
  <div class="panel-heading">
    <h1 class="panel-title topic-title word-ba"><%= title @topic.title %></h1>
    <div class="meta">
      <%= link_to @topic.node.name, @topic.node %>
      •
      <%= @topic.user %>
      •
      于<%= @topic.created_at %>发布
      •
      最后由<%= @topic.last_reply_user %>回复
      •
      <%= @topic.visits %>次阅读
    </div>
  </div>
  <div class="panel-body">
    <div class="topic-body">
      <%= @topic.body.html_safe %>
    </div>
  </div>
</div>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<div class="pull-right">
  <%= paginate @topics %>
</div>
<div class="clearfix"></div>
<% @topics.each do |reply| %>
  <div class="tiezi">
    <table class="table">
      <tr>
        <td>
          <div class="tiezi-user">
            <%= link_to reply.user, reply.user %>
          </div>
        </td>
        <td>
          <div class="tiezi-body">

          </div>
        </td>
      </tr>
    </table>
  </div>
<% end -%>

app/views/topics/new.html.erb
<h1>发贴</h1>
<%= render 'form' %>

app/views/topics/show.html.erb
<%= render "topics/topic_show"%>

<%= render "replies/replies" %>

<%= render "replies/login_or_form", from: [@topic,@topic.replies.new] %>