config/routes.rb
Yeshi::Application.routes.draw do
  use_doorkeeper

  constraints subdomain: ENV['SUBDOMAIN'] do
    resources :nodes do
      resources :topics, only: [:new, :create]
    end
    resources :sections
    resources :topics do
      resources :replies
    end
    resources :articles, only: [:index, :show] do
      get '/tags/:tag', to: 'articles#tag', as: :tag, on: :collection
      get '/tags', to: 'articles#tags', as: :tags, on: :collection
      resources :comments, only: [:index,:create]
    end
    get '/categories/:category', to: 'commodities#category', as: :category
    get '/categories', to: 'commodities#categories', as: :categories
    resources :posts, only: [:index, :show] do
      get :ajax, on: :collection
      resources :comments, only: [:index,:create]
    end
    resources :comments, only: [:index, :show, :create]
    resources :notifications ,except: [:edit,:update,:new,:create] do
      get :read,on: :collection
      #member do 
      #post :accept
      #post :deny
      #end
    end

    resources :chat_messages, only: [:new, :create]
    resources :got_chat_messages, only: [:index, :show, :destroy]
    resources :traders, only: [:index, :show, :create] do
      get :contact, to: 'traders#contact', on: :member
      resources :locations, only: [:index]
      resources :commodities, only: [:index]
      resources :groups, only: [:index]
    end
    resources :groups, only: [:index, :show] do
      resources :commodities, only: [:index]
      resources :comments, only: [:index,:create]
    end

    resources :locations, only: [:index]
    resources :commodities, only: [:index, :show] do
      resources :comments, only: [:index,:create]
    end
    authenticated :user do
      root :to => 'home#index'
    end
    root :to => "home#index"
    get '/contact', :to => "home#contact", as: :system_contact
    get '/download', :to => "home#download", as: :download
  end

  constraints subdomain: ENV['USER_SUBDOMAIN'] do
    devise_for :users, controllers: {
      omniauth_callbacks: :authentications,
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    }
    scope module: 'user' do
      root to: 'home#index', as: :user_home
      #get 'authentications', to: 'home#authentications', as: :user_authentications
      resources :posts do
        get :ajax, on: :collection
      end
      resources :authentications
      resources :chat_messages, only: [:new, :create], as: :user_chat_messages
      resources :got_chat_messages, only: [:index, :show, :destroy], as: :user_got_chat_messages
      resources :commodities, only: [:index, :show] do
        resources :chat_messages, only: [:new, :create]
      end

      resources :comments, only: [:index, :destroy]
      resources :mp_users

    end
  end

  constraints subdomain: ENV['TRADER_SUBDOMAIN'] do
    #devise_for :users
    scope module: 'trader' do
      resources :contacts, except: [:show]
      resources :traders, only: [:index, :create, :update]
      resources :locations, except: [:edit, :update]
      resources :groups do
        resources :commodities
        get :bulk_add, on: :member
        put :bulk_add_commodities, on: :member
      end
      resources :pictures
      resources :bills, except: [:new, :show] do
        get :dashboard, on: :collection
      end
      resources :commodities, except: [:new] do
        resources :bills, only: [:index, :new]
      end
      root :to => 'home#index', as: :trader_home
      get '/dashboard' => 'bills#dashboard'
    end
  end

  constraints subdomain: ENV['ADMIN_SUBDOMAIN'] do
    scope module: 'admin' do
      resources :articles do
        post :publish, on: :member
      end
      resources :apks do
        get :updated_version, on: :member
      end
      resources :users
      resources :ads
      resources :comments
    end
  end

  constraints subdomain: ENV['API_SUBDOMAIN'] do
    scope module: 'api' do
      namespace :v1 do
        # another api routes
        get '/me' => "credentials#me"
        get '/dashboard' => "credentials#dashboard"
        post '/reg' => "registrations#create"
        #post '/test' => "registrations#test"
        resources :got_chat_messages, only: [:index, :show, :destroy]
        resources :chat_messages, only: [:create]
        resources :locations, only: [:index, :create, :destroy]
        resources :business_hours, only: [:index, :create, :update, :destroy]
        resources :groups, only: [:index, :create, :update, :destroy, :show] do
          resources :commodities, only: [:index, :create]
          put :bulk_add_commodities, on: :member
        end

        resources :commodities, only: [:index, :create, :update, :destroy, :show] do
          resources :bills
        end
        resources :bills, only: :index do
          get :dashboard, on: :collection
        end
        #resources :notifications ,except: [:edit,:update,:new,:create] do
          #get :read,on: :collection
          #get :status,on: :collection
          #member do 
            #post :accept
            #post :deny
          #end
        #end
      end
    end
  end

  constraints subdomain: ENV['MP_SUBDOMAIN'] do
    scope module: 'mp' do
      root to: 'home#index', as: :mp, via: [:get]
      post '/' => "home#create"
    end
  end

end

app/models/notification/base.rb
class Notification::Base
  include Mongoid::Document
  include Mongoid::Timestamps
  field :text, type: String
  field :read_at, type: DateTime
  field :deal_at, type: DateTime

  embedded_in :user, :inverse_of => :notifications

  scope :unread,where(read_at: nil)
  scope :read,where(:read_at.exists => true)
  scope :recent,order_by(created_at: :desc)
  scope :oread,order_by(read_at: :asc)

  def has_read?
    !!read_at
  end

  def read!
    update_attribute :read_at,Time.now unless has_read?
  end

  def type_name
    self._type.split('::').last.tableize.singularize
  end

  def deal
    read!
    update_attribute :deal_at,Time.now unless deal_at
  end

  def is_deal?
    !!deal_at
  end

  def destroy
    read!
  end
end

app/models/notification/chat.rb
class Notification::Chat < Notification::Base
  belongs_to :from, :class_name => 'User',inverse_of: nil
  belongs_to :chat_message, :class_name => 'ChatMessage',inverse_of: nil
end

app/controllers/api/v1/notifications_controller.rb
module Api::V1
  class NotificationsController < ApiController
    doorkeeper_for :all
    respond_to :json

    def index
      @notifications = current_resource_owner.notifications.oread.recent.page params[:page]
      render json: @notifications.to_json
    end

    def show
      @notification = current_resource_owner.notifications.find(params[:id])
      @notification.read!
      render json: @notification.to_json
    end

    def status
      render json: {count: current_resource_owner.notifications.unread.count,last: current_resource_owner.notifications.unread.last}.to_json
    end

    def accept
      @notification = current_resource_owner.notifications.find(params[:id])
      if @notification.accept!
        render json: @notification.to_json
      else
        render json: @notification.errors, :status=>422
      end
    end

    def deny
      @notification = current_resource_owner.notifications.find(params[:id])
      if @notification.deny!
        render json: @notification.to_json
      else
        render json: @notification.errors, :status=>422
      end
    end
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < InheritedResources::Base
  before_filter :authenticate_user!
  actions :all,except: [:edit,:update,:new,:create]

  skip_load_and_authorize_resource only: :index

  def show
    show! do 
      @notification.read!
    end
  end

  def read
    @notifications = current_user.notifications.read.recent.page params[:page]
  end

  def destroy
    destroy! do |f|
      f.js
      f.html{redirect_to :back}
    end
  end

  #def accept
    #@notification = current_user.notifications.find(params[:id])
    #@notification.accept!
    #if request.xhr?
      #render :remove_notification
    #else
      #redirect_to :back
    #end

  #end

  #def deny
    #@notification = current_user.notifications.find(params[:id])
    #@notification.deny!
    #if request.xhr?
      #render :remove_notification
    #else
      #redirect_to :back
    #end
  #end

  protected
  def begin_of_association_chain
    current_user
  end

  def collection
    @notifications ||= end_of_association_chain.recent.unread.page params[:page]
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= simple_form_for(@notification) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/notifications/destroy.js.erb
<%= render "remove_div",id:params[:id] %>

app/views/notifications/edit.html.erb
<h1>Editing notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<h1>未读通知</h1>
<ul class="nav nav-pills">
  <li class="active">
    <%= link_to '未读',notifications_path %>
  </li>
  <li>
    <%= link_to '已读',read_notifications_path %>
  </li>
</ul>
<div id="notifications">
  <div class="col-md-11 col-lg-11">
    <% @notifications.each do |notification| %>
      <div class="col-md-10 col-lg-10">
        <%= render_cell :notification,notification.type_name, notification: notification %>
      </div>
      <div class="col-md-1 col-lg-1">
        <%= link_to t('labels.ignore'), notification_path(notification), method: :delete,remote:true,class:'btn btn-info' %>
      </div>
      <div class="divider" style="margin-left: 20px">
      </div>
    <% end %>
  </div>
</div>
<div class="pull-right">
  <%= paginate @notifications %>
</div>

app/views/notifications/new.html.erb
<h1>New notification</h1>

<%= render 'form' %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/read.html.erb
<h1>已读通知</h1>
<ul class="nav nav-pills">
  <li>
    <%= link_to '未读',notifications_path %>
  </li>
  <li class="active">
    <%= link_to '已读',read_notifications_path %>
  </li>
</ul>
<div class="row-fluid" id="notifications">
  <div class="span11">
    <% @notifications.each do |notification| %>
      <div class="row-fluid" id="<%= notification.id%>">
        <div class="span10">
          <%= render_cell :notification,notification.type_name, notification: notification %>
        </div>
        <div class="span1">
          <%#= link_to t('labels.ignore'), notification_path(notification), method: :delete,remote:true,class:'btn btn-info' %>
        </div>
        <div class="divider" style="margin-left: 20px">
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="pull-right">
  <%= paginate @notifications %>
</div>

app/views/notifications/show.html.erb
<%= render_cell :notification,@notification.type_name, notification: @notification %>