config/routes.rb
Yeshi::Application.routes.draw do
  use_doorkeeper

  constraints subdomain: ENV['SUBDOMAIN'] do
    resources :nodes do
      resources :topics, only: [:new, :create]
    end
    resources :sections
    resources :topics do
      resources :replies
    end
    resources :articles, only: [:index, :show] do
      get '/tags/:tag', to: 'articles#tag', as: :tag, on: :collection
      get '/tags', to: 'articles#tags', as: :tags, on: :collection
      resources :comments, only: [:index,:create]
    end
    get '/categories/:category', to: 'commodities#category', as: :category
    get '/categories', to: 'commodities#categories', as: :categories
    resources :posts, only: [:index, :show] do
      get :ajax, on: :collection
      resources :comments, only: [:index,:create]
    end
    resources :comments, only: [:index, :show, :create]
    resources :notifications ,except: [:edit,:update,:new,:create] do
      get :read,on: :collection
      #member do 
      #post :accept
      #post :deny
      #end
    end

    resources :chat_messages, only: [:new, :create]
    resources :got_chat_messages, only: [:index, :show, :destroy]
    resources :traders, only: [:index, :show, :create] do
      get :contact, to: 'traders#contact', on: :member
      resources :locations, only: [:index]
      resources :commodities, only: [:index]
      resources :groups, only: [:index]
    end
    resources :groups, only: [:index, :show] do
      resources :commodities, only: [:index]
      resources :comments, only: [:index,:create]
    end

    resources :locations, only: [:index]
    resources :commodities, only: [:index, :show] do
      resources :comments, only: [:index,:create]
    end
    authenticated :user do
      root :to => 'home#index'
    end
    root :to => "home#index"
    get '/contact', :to => "home#contact", as: :system_contact
    get '/download', :to => "home#download", as: :download
  end

  constraints subdomain: ENV['USER_SUBDOMAIN'] do
    devise_for :users, controllers: {
      omniauth_callbacks: :authentications,
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    }
    scope module: 'user' do
      root to: 'home#index', as: :user_home
      #get 'authentications', to: 'home#authentications', as: :user_authentications
      resources :posts do
        get :ajax, on: :collection
      end
      resources :authentications
      resources :chat_messages, only: [:new, :create], as: :user_chat_messages
      resources :got_chat_messages, only: [:index, :show, :destroy], as: :user_got_chat_messages
      resources :commodities, only: [:index, :show] do
        resources :chat_messages, only: [:new, :create]
      end

      resources :comments, only: [:index, :destroy]
      resources :mp_users

    end
  end

  constraints subdomain: ENV['TRADER_SUBDOMAIN'] do
    #devise_for :users
    scope module: 'trader' do
      resources :contacts, except: [:show]
      resources :traders, only: [:index, :create, :update]
      resources :locations, except: [:edit, :update]
      resources :groups do
        resources :commodities
        get :bulk_add, on: :member
        put :bulk_add_commodities, on: :member
      end
      resources :pictures
      resources :bills, except: [:new, :show] do
        get :dashboard, on: :collection
      end
      resources :commodities, except: [:new] do
        resources :bills, only: [:index, :new]
      end
      root :to => 'home#index', as: :trader_home
      get '/dashboard' => 'bills#dashboard'
    end
  end

  constraints subdomain: ENV['ADMIN_SUBDOMAIN'] do
    scope module: 'admin' do
      resources :articles do
        post :publish, on: :member
      end
      resources :apks do
        get :updated_version, on: :member
      end
      resources :users
      resources :ads
      resources :comments
    end
  end

  constraints subdomain: ENV['API_SUBDOMAIN'] do
    scope module: 'api' do
      namespace :v1 do
        # another api routes
        get '/me' => "credentials#me"
        get '/dashboard' => "credentials#dashboard"
        post '/reg' => "registrations#create"
        #post '/test' => "registrations#test"
        resources :got_chat_messages, only: [:index, :show, :destroy]
        resources :chat_messages, only: [:create]
        resources :locations, only: [:index, :create, :destroy]
        resources :business_hours, only: [:index, :create, :update, :destroy]
        resources :groups, only: [:index, :create, :update, :destroy, :show] do
          resources :commodities, only: [:index, :create]
          put :bulk_add_commodities, on: :member
        end

        resources :commodities, only: [:index, :create, :update, :destroy, :show] do
          resources :bills
        end
        resources :bills, only: :index do
          get :dashboard, on: :collection
        end
        #resources :notifications ,except: [:edit,:update,:new,:create] do
          #get :read,on: :collection
          #get :status,on: :collection
          #member do 
            #post :accept
            #post :deny
          #end
        #end
      end
    end
  end

  constraints subdomain: ENV['MP_SUBDOMAIN'] do
    scope module: 'mp' do
      root to: 'home#index', as: :mp, via: [:get]
      post '/' => "home#create"
    end
  end

end

app/models/apk.rb
class Apk
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  field :name, type: String
  field :english_name, type: String
  field :version, type: String, default: '1.00'
  field :update_info, type: String, default: ''
  field :order, type: Integer,default: 0
  mount_uploader :apk, ApkUploader

  scope :recent, desc(:created_at)
  scope :download, desc(:order).desc(:created_at)

  def updated_version
    Apk.new name: self.name, english_name: self.english_name, version: (self.version.to_f + 0.01).to_s, update_info: self.update_info, order: self.order
  end
end

app/controllers/admin/apks_controller.rb
class Admin::ApksController < InheritedResources::Base
  before_filter :authenticate_admin!
  layout 'left_nav'

  def create
    create!{apks_path}
  end

  def update
    update!{apks_path}
  end

  def updated_version
    @apk = Apk.find(params[:id]).updated_version
  end

  protected
  def collection
    @apks ||= end_of_association_chain.accessible_by(current_ability).download.page params[:page]
  end
end

app/helpers/admin/apks_helper.rb
module Admin::ApksHelper
end

app/views/admin/apks/_form.html.erb
<%= simple_form_for(@apk) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :english_name %>
    <%= f.input :version %>
    <%= f.input :update_info, as: :text, input_html: {class: :wysihtml5} %>
    <%= f.input :order %>
    <%= f.input :apk %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/apks/edit.html.erb
<h1>Editing apk</h1>

<%= render 'form' %>

<%= link_to 'Show', @apk %> |
<%= link_to 'Back', apks_path %>

app/views/admin/apks/index.html.erb
<h1>Listing apks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>English name</th>
    <th>Version</th>
    <th>Update info</th>
    <th>排序级别</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @apks.each do |apk| %>
  <tr>
    <td><%= apk.name %></td>
    <td><%= apk.english_name %></td>
    <td><%= apk.version %></td>
    <td><%= apk.update_info %></td>
    <td><%= apk.order %></td>
    <td><%= link_to '更新版本', updated_version_apk_path(apk) %></td>
    <td><%= link_to 'Edit', edit_apk_path(apk) %></td>
    <td><%= link_to 'Destroy', apk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<div class="clearfix"></div>
<div class="pull-right">
  <%= paginate @apks %>
</div>

<br />

<%= link_to 'New Apk', new_apk_path %>

app/views/admin/apks/new.html.erb
<h1>New apk</h1>

<%= render 'form' %>

<%= link_to 'Back', apks_path %>

app/views/admin/apks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @apk.name %>
</p>

<p>
  <b>English name:</b>
  <%= @apk.english_name %>
</p>

<p>
  <b>Version:</b>
  <%= @apk.version %>
</p>

<p>
  <b>Update info:</b>
  <%= @apk.update_info %>
</p>


<%= link_to 'Edit', edit_apk_path(@apk) %> |
<%= link_to 'Back', apks_path %>

app/views/admin/apks/updated_version.html.erb
<h1>更新内容</h1>

<%= render 'form' %>

<%= link_to 'Back', apks_path %>